"""empty message

Revision ID: 82706d56af8e
Revises: db05b9c8d6dd
Create Date: 2021-11-03 14:55:16.248933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82706d56af8e'
down_revision = 'db05b9c8d6dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pokemon_user_id_fkey', 'pokemon', type_='foreignkey')
    op.drop_column('pokemon', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pokemon_user_id_fkey', 'pokemon', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
