"""empty message

Revision ID: 856b006b8843
Revises: 82706d56af8e
Create Date: 2021-11-03 14:55:55.442812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856b006b8843'
down_revision = '82706d56af8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pokemon', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pokemon', type_='foreignkey')
    op.drop_column('pokemon', 'user_id')
    # ### end Alembic commands ###
